spring:
  application:
    name: liberty-utils

  datasource:
    url: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}?sslmode=prefer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      auto-commit: false
      idle-timeout: 300000  # 5 minutes
      max-lifetime: 600000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yml

  jpa:
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
    hibernate:
      ddl-auto: none

okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
  client:
    org-url: https://${OKTA_DOMAIN}
    token: ${OKTA_API_TOKEN}

server:
  port: ${PORT:8080}
  error:
    include-message: always
