include:
  - postgres-compose.yml

services:
  liberty-utils-server:
    image: ezraorina834/liberty-utils-server:${APP_VERSION}
    restart: unless-stopped
    environment:
      CORS_PATTERNS: "${CORS_PATTERNS}"
      DB_DOMAIN: "${DB_DOMAIN}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_INTERNAL_PORT}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USERNAME: "${DB_USERNAME}"
      OKTA_CLIENT_ID: "${OKTA_CLIENT_ID}"
      OKTA_CLIENT_SECRET: "${OKTA_CLIENT_SECRET}"
      OKTA_DOMAIN: "${OKTA_DOMAIN}"
      PORT: "${PORT}"
      SHOW_SQL: "${SHOW_SQL}"
      OKTA_API_TOKEN: "${OKTA_API_TOKEN}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.liberty-${ENV}.rule=Host(`liberty-utils-server-${ENV}.ezra-home.me`)"
      - "traefik.http.routers.liberty-${ENV}.entrypoints=websecure"
      - "traefik.http.routers.liberty-${ENV}.tls=true"
      - "traefik.http.routers.liberty-${ENV}.tls.certresolver=acme-cert-resolver"
      - "traefik.http.services.liberty-${ENV}.loadbalancer.server.port=${PORT}"

    networks:
      - ezra-home
      - default

    depends_on:
      - postgres-liberty-utils

networks:
  ezra-home:
    external: true
